# Generated by Django 2.0.8 on 2018-11-08 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abbreviation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=200)),
                ('full_form', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='AbbreviationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NoteText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(max_length=3000)),
                ('coverted_text', models.TextField(max_length=3000)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='abbreviation',
            name='abbreviation_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.AbbreviationList'),
        ),
    ]
