# Generated by Django 2.0.8 on 2018-11-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notetext',
            name='coverted_text',
            field=models.TextField(default='type in text to convert', max_length=3000),
        ),
        migrations.AlterField(
            model_name='notetext',
            name='raw_text',
            field=models.TextField(default='type in text to convert', max_length=3000),
        ),
    ]
